### ISSUE TITLE
About the generalize ability of GwcNet.

### ISSUE THREAD

**Issue by gangweix** [jiaw-z/FeatureConsistentStereo#4]
I test generalize ability of GwcNet on KITTI and Middlebury using the official pretrained model, the result is 12.5% on KITTI 2012, 12.4% on KITTI 2015. But in your paper, it is 20.2% and 22.7%. Can I know how you tested?

**Comment by jiaw-z** [comment]
> I test generalize ability of GwcNet on KITTI and Middlebury using the official pretrained model, the result is 12.5% on KITTI 2012, 12.4% on KITTI 2015. But in your paper, it is 20.2% and 22.7%. Can I know how you tested?

Very sorry to reply late. It puzzles us as well. It seems our retrained GWCNet gets a different generalization performance than the official pre-trained checkpoint despite we follow the original implementation. Since we observe similar results in other works(DSMNet...), we report the results in our experiments.

**Comment by colorfulgreen** [comment]
[NOTICE] Zhang Jiawei(Gary) deleted my workspace without notice, which containes data and network models of a paper under review.

<img width="646" alt="image" src="https://github.com/jiaw-z/FCStereo/assets/2982465/16a700d3-56de-431b-9c78-43dea07a3e5e">
